# Generated by Django 3.0.7 on 2020-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korotron', '0003_auto_20200626_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryservice',
            name='link',
            field=models.CharField(default='pk', max_length=50, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(blank=True, verbose_name='Цена (руб.)'),
        ),
    ]
