# Generated by Django 3.0.7 on 2020-06-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korotron', '0004_auto_20200626_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryservice',
            name='link',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Ссылка'),
        ),
    ]
