# Generated by Django 3.0.7 on 2020-06-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korotron', '0005_auto_20200626_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
