# Generated by Django 3.0.7 on 2020-06-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korotron', '0007_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
