# Generated by Django 3.0.7 on 2020-06-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korotron', '0009_auto_20200629_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-title'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
