# Generated by Django 3.0.7 on 2020-06-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korotron', '0010_auto_20200630_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryservice',
            options={'ordering': ['pk'], 'verbose_name': 'Категория услуг', 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
